# Generated by Django 5.1 on 2025-08-24 16:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_resumetemplate_certification_education_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeanalytics',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Resume Analytics'},
        ),
        migrations.RemoveField(
            model_name='resumeanalytics',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='resumeanalytics',
            name='last_viewed',
        ),
        migrations.RemoveField(
            model_name='resumeanalytics',
            name='views',
        ),
        migrations.AddField(
            model_name='resume',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='share_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeanalytics',
            name='action',
            field=models.CharField(choices=[('viewed', 'Viewed'), ('pdf_generated', 'PDF Generated'), ('duplicated', 'Duplicated'), ('share_status_changed', 'Share Status Changed')], default='viewed', max_length=50),
        ),
        migrations.AddField(
            model_name='resumeanalytics',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resumeanalytics',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='css_template',
            field=models.CharField(default='classic.css', max_length=100),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='html_template',
            field=models.CharField(default='classic.html', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_resumes', to='builder.userprofile'),
        ),
        migrations.AlterField(
            model_name='resumeanalytics',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resumeanalytics',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_entries', to='builder.resume'),
        ),
    ]
