# Generated by Django 5.1 on 2025-08-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_resumeanalytics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='category',
            field=models.CharField(choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('creative', 'Creative'), ('executive', 'Executive')], default='modern', max_length=20),
        ),
    ]
